/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.TransaksiItem;
import com.Obat;
import db.ConnectionManager;
import exec.ExecuteTransaksiItem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import object.ConvertTransaksiItemToObject;

/**
 *
 * @author ALIK
 */
public class TransaksiDetail extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiItem
     */
    public TransaksiDetail() {
        initComponents();
    }
    public TransaksiDetail(int id_transaksi, int id_admin) {
        initComponents();
        this.id_transaksi = id_transaksi;
        this.id_admin = id_admin;
        setDataTransaksiItem(id_transaksi);
    }
    public int id_transaksi, id_admin, id_transaksi_item;
    
    private void setDataTransaksiItem(int id_transaksi){
        ConvertTransaksiItemToObject cpto = new ConvertTransaksiItemToObject();
        String[][] dataTransaksiItem = cpto.getTransaksi(id_transaksi);
        tblTransaksiItem.setModel(new javax.swing.table.DefaultTableModel(
            dataTransaksiItem,
            new String [] {
                "ID Transaksi Item", "ID Transaksi", "ID Obat", "Qty", "Subtotal", "Obat", "Invoice"
            }
        ));
        jScrollPane1.setViewportView(tblTransaksiItem);
        PreparedStatement ps;
        try{
            ConnectionManager conMan = new ConnectionManager();
            Connection conn = conMan.logOn();
            ps = conn.prepareStatement("select * from obat");
            Vector<Obat> vector = new Vector<>();
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                  vector.addElement(new Obat(rs.getInt(1), rs.getString(2), rs.getInt(3)));
                  cbbObat.setModel(new DefaultComboBoxModel(vector));
            }
        }catch(SQLException sQLException){
            sQLException.printStackTrace();
        }
    }
    
    private void setTotal(){
        PreparedStatement ps;
        PreparedStatement ps2;
        try{
            ConnectionManager conMan = new ConnectionManager();
            Connection conn = conMan.logOn();
            ps = conn.prepareStatement("select SUM(subtotal) AS total from transaksi_item where id_transaksi=?");
            ps.setInt(1, this.id_transaksi);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                int total = rs.getInt("total");
                ps2 = conn.prepareStatement("update transaksi set total=? where id_transaksi=?");
                ps2.setInt(1, total);
                ps2.setInt(2, this.id_transaksi);
                int hasil = ps2.executeUpdate();
                if(hasil > 0){
                    JOptionPane.showMessageDialog(null, "Total harga telah diubah menjadi " + total);
                }
            }
        }catch(SQLException exception){
            exception.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInputTransaksiItem = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQtyTransaksiItem = new javax.swing.JTextField();
        txtSubtotalTransaksiItem = new javax.swing.JTextField();
        cbbObat = new javax.swing.JComboBox<>();
        btnSubmitItem = new javax.swing.JButton();
        btnUpdateItem = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        pnlTabelTransaksiItem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksiItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("ID Obat");

        jLabel3.setText("Quantity");

        jLabel4.setText("Subtotal");

        txtQtyTransaksiItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyTransaksiItemKeyReleased(evt);
            }
        });

        btnSubmitItem.setText("Submit");
        btnSubmitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitItemActionPerformed(evt);
            }
        });

        btnUpdateItem.setText("Update");
        btnUpdateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Delete");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputTransaksiItemLayout = new javax.swing.GroupLayout(pnlInputTransaksiItem);
        pnlInputTransaksiItem.setLayout(pnlInputTransaksiItemLayout);
        pnlInputTransaksiItemLayout.setHorizontalGroup(
            pnlInputTransaksiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputTransaksiItemLayout.createSequentialGroup()
                .addGroup(pnlInputTransaksiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputTransaksiItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlInputTransaksiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInputTransaksiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(txtQtyTransaksiItem, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(txtSubtotalTransaksiItem, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(cbbObat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlInputTransaksiItemLayout.createSequentialGroup()
                                .addComponent(btnSubmitItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteItem))))
                    .addGroup(pnlInputTransaksiItemLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlInputTransaksiItemLayout.setVerticalGroup(
            pnlInputTransaksiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputTransaksiItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQtyTransaksiItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubtotalTransaksiItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlInputTransaksiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitItem)
                    .addComponent(btnUpdateItem)
                    .addComponent(btnDeleteItem))
                .addGap(18, 18, 18)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTabelTransaksiItemLayout = new javax.swing.GroupLayout(pnlTabelTransaksiItem);
        pnlTabelTransaksiItem.setLayout(pnlTabelTransaksiItemLayout);
        pnlTabelTransaksiItemLayout.setHorizontalGroup(
            pnlTabelTransaksiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTabelTransaksiItemLayout.setVerticalGroup(
            pnlTabelTransaksiItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblTransaksiItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksiItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksiItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(pnlTabelTransaksiItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlInputTransaksiItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInputTransaksiItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabelTransaksiItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitItemActionPerformed
        // TODO add your handling code here:
        String qty = txtQtyTransaksiItem.getText();
        String subtotal = txtSubtotalTransaksiItem.getText();
        int id_obat = ((Obat)cbbObat.getSelectedItem()).getId_obat();
        TransaksiItem t = new TransaksiItem(this.id_transaksi, id_obat, Integer.parseInt(qty), Integer.parseInt(subtotal));
        ExecuteTransaksiItem ex = new ExecuteTransaksiItem();
        int hasil = ex.insertData(t);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDataTransaksiItem(this.id_transaksi);
            setTotal();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnSubmitItemActionPerformed

    private void tblTransaksiItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiItemMouseClicked
        // TODO add your handling code here:
        int row = tblTransaksiItem.getSelectedRow();
        String id = tblTransaksiItem.getValueAt(row, 0).toString();
        String id_transaksi = tblTransaksiItem.getValueAt(row, 1).toString();
        String id_obat = tblTransaksiItem.getValueAt(row, 2).toString();
        String qty = tblTransaksiItem.getValueAt(row, 3).toString();
        String subtotal = tblTransaksiItem.getValueAt(row, 4).toString();
        this.id_transaksi_item = Integer.parseInt(id);
        txtQtyTransaksiItem.setText(qty);
        txtSubtotalTransaksiItem.setText(subtotal);
    }//GEN-LAST:event_tblTransaksiItemMouseClicked

    private void btnUpdateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemActionPerformed
        // TODO add your handling code here:
        String qty = txtQtyTransaksiItem.getText();
        String subtotal = txtSubtotalTransaksiItem.getText();
        int id_obat = ((Obat)cbbObat.getSelectedItem()).getId_obat();
        TransaksiItem t = new TransaksiItem(this.id_transaksi_item, this.id_transaksi, id_obat, Integer.parseInt(qty), Integer.parseInt(subtotal));
        ExecuteTransaksiItem ex = new ExecuteTransaksiItem();
        int hasil = ex.ubahData(t);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
            setDataTransaksiItem(this.id_transaksi);
            setTotal();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di ubah");
        }
    }//GEN-LAST:event_btnUpdateItemActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
        ExecuteTransaksiItem ex = new ExecuteTransaksiItem();
        int hasil = ex.hapusData(this.id_transaksi_item);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDataTransaksiItem(this.id_transaksi);
            setTotal();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        Main main = new Main(id_admin);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtQtyTransaksiItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyTransaksiItemKeyReleased
        // TODO add your handling code here:
        int harga = ((Obat)cbbObat.getSelectedItem()).getHarga();
        int qty = 0;
        if(txtQtyTransaksiItem.getText().equals("")){
            qty = 0;
            txtSubtotalTransaksiItem.setText(""+qty*harga);
        }else{
            qty = Integer.parseInt(txtQtyTransaksiItem.getText());
            txtSubtotalTransaksiItem.setText(""+qty*harga);
        }
    }//GEN-LAST:event_txtQtyTransaksiItemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSubmitItem;
    private javax.swing.JButton btnUpdateItem;
    private javax.swing.JComboBox<String> cbbObat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlInputTransaksiItem;
    private javax.swing.JPanel pnlTabelTransaksiItem;
    private javax.swing.JTable tblTransaksiItem;
    private javax.swing.JTextField txtQtyTransaksiItem;
    private javax.swing.JTextField txtSubtotalTransaksiItem;
    // End of variables declaration//GEN-END:variables
}
